POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4NzRlZmUzYmFmMDIxNjU2YWQ0ZDI5MCIsImlhdCI6MTc1MjQ5NjQ4OH0.wzPrHt21ZcJMg8exlX1rCnqlATWFcbwNPhELnWl2-_8

{
  "title" : "How to live",
  "author" : "Dale Carniege",
  "url" : "randomurl.com",
  "likes" : 999,
  "userId": "6874efe3baf021656ad4d290"
}