POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4NzRmZWM0Y2JlNjgyMzk4Y2RmMmNkMSIsImlhdCI6MTc1MjQ5OTEwM30.0n6aZq0ifXUElCxJzReWpsQqk3GHFUqMUUZTtDsycec

{
  "title" : "How to live",
  "author" : "Dale Carniege",
  "url" : "randomurl.com",
  "likes" : 999
}