POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title" : "How to live",
  "author" : "Dale Carniege",
  "url" : "randomurl.com",
  "likes" : 999,
  "userId": "6874efe3baf021656ad4d290"
}