POST https://wljzfk-3001.csb.app/api/persons/
Content-Type: application/json

{
  "name": "Johhny",
  "number": "010101010"
}

###
POST https://wljzfk-3001.csb.app/api/persons/
Content-Type: application/json

{
  "name": "Johhny",
  "number": "010101010"
}